### ISSUE TITLE
The address is too large causing an addition error

### ISSUE THREAD

**Issue by busihuoniao** [HongThatCong/RelocEditor#1]
64-bit DLL files
Add address: 1802E4FE3

![S)K6P$1CK3LZC~JXF@QE@F7](https://github.com/user-attachments/assets/eb939190-e8e8-4cf2-a096-22834f02c157)

**Comment by busihuoniao** [comment]
![Uploading S)K6P$1CK3LZC~JXF@QE@F7.png…]()

**Comment by HongThatCong** [comment]
can you upload that PE file here?
Maybe that PE file has an error in the .reloc section
Tks

**Comment by busihuoniao** [comment]
> can you upload that PE file here? Maybe that PE file has an error in the .reloc section Tks

UInt64 page = (address & 0xFFFFF000) - pehr.GetImageBase32Or64();
Change to
UInt64 page = (address & 0xFFFFFFFFF000) - pehr.GetImageBase32Or64();
Fixed
This is because the ImageBase width is limited.

**Comment by HongThatCong** [comment]
Tks, code updated
